version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    depends_on:
      - django_app
    restart: always
    networks:
      - mynetwork

  django_app:
    build:
      context: .
    container_name: "django_cont"
    ports:
      -  "8000:8000"
    env_file:
      - ".env"
    depends_on:
      - mysql
    restart: always
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mynetwork

  mysql:
    image: mysql
    container_name: mysql_cont
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Pass@123
      MYSQL_DATABASE: notes_db
    networks:
      - mynetwork
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pPass@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  mynetwork:

volumes:
  mysql-data:
